# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
    efsks \
    ks \
    mpdecision \
    netmgrd \
    qcks \
    qmuxd \
    qrngd \
    qseecomd \
    rmt_storage \
    ta2bin \
    ta_qmi_client \
    taimport \
    thermald \
    a225_pfp \
    a225_pm4 \
    a225p5_pm4 \
    a300_pfp \
    a300_pm4 \
    acdb \
    cyttsp_8064_mtp \
    cyttsp_8960_cdp \
    dsp1 \
    dsp2 \
    dsp3 \
    dsps_b00 \
    dsps_b01 \
    dsps_b02 \
    dsps_b03 \
    dsps_b04 \
    dsps_b05 \
    dsps_flist \
    dsps_mdt \
    dxhdcp2_b00 \
    dxhdcp2_b01 \
    dxhdcp2_b02 \
    dxhdcp2_b03 \
    dxhdcp2_flist \
    dxhdcp2_mdt \
    leia_pfp_470 \
    leia_pm4_470 \
    mdm_acdb \
    ta \
    tzlibasb_b00 \
    tzlibasb_b01 \
    tzlibasb_b02 \
    tzlibasb_b03 \
    tzlibasb_flist \
    tzlibasb_mdt \
    tzsuntory_b00 \
    tzsuntory_b01 \
    tzsuntory_b02 \
    tzsuntory_b03 \
    tzsuntory_flist \
    tzsuntory_mdt \
    vidc_b00 \
    vidc_b01 \
    vidc_b02 \
    vidc_b03 \
    vidc_mdt \
    vidc_1080p \
    vidcfw \
    wcd9310_anc \
    wcd9310_mbhc \
    wcnss_b00 \
    wcnss_b01 \
    wcnss_b02 \
    wcnss_b04 \
    wcnss_b05 \
    wcnss_flist \
    wcnss_mdt \
    WCNSS_cfg \
    WCNSS_qcom_cfg \
    WCNSS_qcom_wlan_nv \
    thermald_conf \
    DxHDCP_cfg \
    egl \
    eglsubAndroid \
    libEGL_adreno200 \
    libGLESv1_CM_adreno200 \
    libGLESv2S3D_adreno200 \
    libGLESv2_adreno200 \
    libq3dtools_adreno200 \
    copybit.msm8960 \
    gralloc.msm8960 \
    hwcomposer.msm8960 \
    lights.default \
    libC2D2 \
    libCB \
    libDivxDrm \
    libI420colorconvert \
    libMcClientQC \
    libMcRegistryQC \
    libNimsWrap \
    libOmxCore \
    libOmxEvrcDec \
    libOmxQcelp13Dec \
    libOmxVdec \
    libOpenCL \
    libOpenVG \
    libP11KeypadJni \
    libP11Notify \
    libPKCS11Wrapper \
    libPaApiQC \
    libQSEEComAPI \
    libSHIMDivxDrm \
    libSSEPKCS11 \
    lib_dlb_msd \
    libacdbloader \
    libadsprpc \
    libalarmservice_jni \
    libals \
    libaudcal \
    libc2d2_a3xx \
    libc2d2_z180 \
    libc2dcolorconvert \
    libcameralight \
    libcneapiclient \
    libcneutils \
    libcsd-client \
    libdiag \
    libdivxdrmdecrypt \
    libdrmdecrypt \
    libdrmdiag \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libexternal \
    libfastcvopt \
    libgenlock \
    libgeofence \
    libgsl \
    libidl \
    liblights-core \
    libllvm-a3xx \
    libllvm-arm \
    libloc_api_v02 \
    libmemalloc \
    libmercury \
    libmiscta \
    libmm-abl \
    libmm-audio-resampler \
    libmm-color-convertor \
    libmmQSM \
    libmmcamera_hdr_lib \
    libmmcamera_image_stab \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_wrapper \
    libmmcamera_wavelet_lib \
    libmmjpeg \
    libmsapm_jni \
    libmsapu_jni \
    libnetmgr \
    liboverlay \
    libpin-cache \
    libprofiler_msmadc \
    libqc-opt \
    libqcci_adc \
    libqcci_legacy \
    libqcgesture \
    libqdMetaData \
    libqdi \
    libqdp \
    libqdutils \
    libqmi \
    libqmi_cci \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqservice \
    libquipc_os_api \
    libquipc_ulp_adapter \
    libril-qc-qmi-1 \
    libril-qcril-hook-oem \
    librmp \
    libsc-a2xx \
    libsc-a3xx \
    libsrsprocessing \
    libstagefrighthw \
    libsys-utils \
    libta \
    libtzplayready \
    libulp2 \
    libwifiscanner \
    libxt_v02 \
    libxtwifi_ulp_adaptor \
    libxtwifi_zpp_adaptor \
    tad_static
